[package]
name = "link_router"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.34", features = ["derive"] }
regex = "1.11.1"
serde = {version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
